### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by CBHhD** [DAMO-NLP-SG/ContProto#1]
Hi, I'm interested in your work. However, when I tried to run this model, it seemed that the radom_seed and eval_metric files are missing in the project so the scripts "sh run_generate_pseudo.sh de conll03" could not run correctly. Could you update these files? Thanks!

**Comment by RandyZhouRan** [comment]
Thank you for your interest in our work. We have uploaded the missing file, please try again now.
